### PR TITLE
feat (translation): implement translate abangkuhhh 🔥🫡 🇮🇩🇬🇧

### PR DESCRIPTION
**Pull request by softone-as**
implement translation abangdaa 🇮🇩🇬🇧🔝

image

### CODE REVIEW

**Comment by softone-as** [comment]
gabisa cek error buildnya bangdaa @zakiego

**Comment by zakiego** [comment]
Hey, look this crazy thing @rzkiypratama @zekhoi 🤯🔥🔥

**Comment by zakiego** [comment]
LGTM, SUPER MENYALA ABANGDA @softone-as 🔥

THANK YOU!!!!! ⚡️⚡️🫡

**Comment by zakiego** [comment]
Maaf sekali ternyata lupa matiin protection preview

Sekarang preview sudah bisa dilihat, meski tanpa login 🙇‍♂️

**Comment by zakiego** [comment]
Just wanted to inform you that I just found out when the shuffle is placed on the client (#20), it causes unexpected behavior, but it's okay, I've fixed it 🤙🏻

**Comment by softone-as** [comment]
ahh thanks for the fix, menyala abangdaa 🔝🌾

**Comment by Kayyies** [comment]
Manyala Abangda

**Pull request merged**
