### PR TITLE
feat: add english version abangkuh ee still rice science 🌾🌾

### PR DESCRIPTION
**Pull request by rzkiypratama**

### CODE REVIEW

**Comment by zekhoi** [comment]
LGTM!

**Comment by zakiego** [comment]
KASIH KERAS ABANGKUUU 🔥

**Comment by zakiego** [comment]
LGTM KAH @zekhoi

**Comment by zakiego** [comment]
LANGSUNGKANNNNN

**Comment by zekhoi** [comment]
still rice science 🌾🌾

**Comment by rzkiypratama** [comment]
THX! LFG!

**Pull request merged**
